spring:
  application:
    name: eurekaserver

  security:
    basic:
      enabled: true
    user:
      name: coursems-eureka-user
      password: senhailustrativa123

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



